### ISSUE TITLE
Cannot copy '../@deep-foundation/deeplinks/call.cjs' to a subdirectory of itself, '../@deep-foundation/deeplinks/call.cjs'

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/npm-automation#35]
```
freephoenix888@FreePhoenix888:~/Programming/deep/deepcase$ DEBUG=* npx npm-pull
  @deep-foundation/npm-automation:npmPullCli { cliOptions: { _: [], '$0': 'node_modules/.bin/npm-pull' } } +0ms
  @deep-foundation/npm-automation:npm-pull { param: { packageName: undefined, packageVersion: undefined } } +0ms
  @deep-foundation/npm-automation:npm-pull { currentDir: '/home/freephoenix888/Programming/deep/deepcase' } +0ms
  @deep-foundation/npm-automation:npm-pull {
  @deep-foundation/npm-automation:npm-pull   packageJsonFilePath: '/home/freephoenix888/Programming/deep/deepcase/package.json'
  @deep-foundation/npm-automation:npm-pull } +0ms
  @deep-foundation/npm-automation:npm-pull { packageName: '@deep-foundation/deepcase', packageVersion: 'latest' } +2ms
[16:20:01.225] git diff
diff --git a/package.json b/package.json
index 1fa45198..b6a72c9c 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "@deep-foundation/deepcase",
-  "version": "0.0.98",
+  "version": "0.0.99",
   "license": "Unlicense",
   "type": "module",
   "keywords": [
@@ -23,8 +23,8 @@
     "@chakra-ui/react": "^2.6.1",
     "@chakra-ui/theme-tools": "^2.0.16",
     "@deep-foundation/core": "~0.0.2",
-    "@deep-foundation/deeplinks": "^0.0.323",
-    "@deep-foundation/tsx": "~0.0.3",
+    "@deep-foundation/deeplinks": "^0.0.322",
+    "@deep-foundation/tsx": "~0.0.5",
     "@emotion/react": "^11.11.0",
     "@emotion/styled": "^11.11.0",
     "@monaco-editor/react": "^4.5.1",
@@ -84,7 +84,6 @@
     "react-i18next": "^13.2.2",
     "react-icons": "^4.8.0",
     "react-linkify": "^1.0.0-alpha",
-    "react-multi-date-picker": "^4.4.1",
     "react-resize-detector": "^9.1.0",
     "react-yandex-metrika": "^2.6.0",
     "recharts": "^2.8.0",
@@ -110,4 +109,4 @@
     "depcheck": "^1.4.3",
     "ts-node": "^10.9.1"
   }
-}
+}
\ No newline at end of file
  @deep-foundation/npm-automation:npm-pull {
  @deep-foundation/npm-automation:npm-pull   gitDiffExecResult: {
  @deep-foundation/npm-automation:npm-pull     command: 'git diff',
  @deep-foundation/npm-automation:npm-pull     escapedCommand: 'git diff',
  @deep-foundation/npm-automation:npm-pull     exitCode: 0,
  @deep-foundation/npm-automation:npm-pull     stdout: 'diff --git a/package.json b/package.json\n' +
  @deep-foundation/npm-automation:npm-pull       'index 1fa45198..b6a72c9c 100644\n' +
  @deep-foundation/npm-automation:npm-pull       '--- a/package.json\n' +
  @deep-foundation/npm-automation:npm-pull       '+++ b/package.json\n' +
  @deep-foundation/npm-automation:npm-pull       '@@ -1,6 +1,6 @@\n' +
  @deep-foundation/npm-automation:npm-pull       ' {\n' +
  @deep-foundation/npm-automation:npm-pull       '   "name": "@deep-foundation/deepcase",\n' +
  @deep-foundation/npm-automation:npm-pull       '-  "version": "0.0.98",\n' +
  @deep-foundation/npm-automation:npm-pull       '+  "version": "0.0.99",\n' +
  @deep-foundation/npm-automation:npm-pull       '   "license": "Unlicense",\n' +
  @deep-foundation/npm-automation:npm-pull       '   "type": "module",\n' +
  @deep-foundation/npm-automation:npm-pull       '   "keywords": [\n' +
  @deep-foundation/npm-automation:npm-pull       '@@ -23,8 +23,8 @@\n' +
  @deep-foundation/npm-automation:npm-pull       '     "@chakra-ui/react": "^2.6.1",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "@chakra-ui/theme-tools": "^2.0.16",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "@deep-foundation/core": "~0.0.2",\n' +
  @deep-foundation/npm-automation:npm-pull       '-    "@deep-foundation/deeplinks": "^0.0.323",\n' +
  @deep-foundation/npm-automation:npm-pull       '-    "@deep-foundation/tsx": "~0.0.3",\n' +
  @deep-foundation/npm-automation:npm-pull       '+    "@deep-foundation/deeplinks": "^0.0.322",\n' +
  @deep-foundation/npm-automation:npm-pull       '+    "@deep-foundation/tsx": "~0.0.5",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "@emotion/react": "^11.11.0",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "@emotion/styled": "^11.11.0",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "@monaco-editor/react": "^4.5.1",\n' +
  @deep-foundation/npm-automation:npm-pull       '@@ -84,7 +84,6 @@\n' +
  @deep-foundation/npm-automation:npm-pull       '     "react-i18next": "^13.2.2",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "react-icons": "^4.8.0",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "react-linkify": "^1.0.0-alpha",\n' +
  @deep-foundation/npm-automation:npm-pull       '-    "react-multi-date-picker": "^4.4.1",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "react-resize-detector": "^9.1.0",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "react-yandex-metrika": "^2.6.0",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "recharts": "^2.8.0",\n' +
  @deep-foundation/npm-automation:npm-pull       '@@ -110,4 +109,4 @@\n' +
  @deep-foundation/npm-automation:npm-pull       '     "depcheck": "^1.4.3",\n' +
  @deep-foundation/npm-automation:npm-pull       '     "ts-node": "^10.9.1"\n' +
  @deep-foundation/npm-automation:npm-pull       '   }\n' +
  @deep-foundation/npm-automation:npm-pull       '-}\n' +
  @deep-foundation/npm-automation:npm-pull       '+}\n' +
  @deep-foundation/npm-automation:npm-pull       '\\ No newline at end of file',
  @deep-foundation/npm-automation:npm-pull     stderr: '',
  @deep-foundation/npm-automation:npm-pull     all: undefined,
  @deep-foundation/npm-automation:npm-pull     failed: false,
  @deep-foundation/npm-automation:npm-pull     timedOut: false,
  @deep-foundation/npm-automation:npm-pull     isCanceled: false,
  @deep-foundation/npm-automation:npm-pull     killed: false
  @deep-foundation/npm-automation:npm-pull   }
  @deep-foundation/npm-automation:npm-pull } +27ms
file:///home/freephoenix888/Programming/deep/deepcase/node_modules/@deep-foundation/npm-automation/dist/npm-pull.js:34
        throw new Error('You have unstaged changes. Stash (git stash) or commit (git commit) them');
              ^

Error: You have unstaged changes. Stash (git stash) or commit (git commit) them
    at npmPull (file:///home/freephoenix888/Programming/deep/deepcase/node_modules/@deep-foundation/npm-automation/dist/npm-pull.js:34:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async npmPullCli (file:///home/freephoenix888/Programming/deep/deepcase/node_modules/@deep-foundation/npm-automation/dist/cli/npm-pull.js:24:5)

Node.js v18.17.1
freephoenix888@FreePhoenix888:~/Programming/deep/deepcase$ DEBUG=* npx npm-pull
  @deep-foundation/npm-automation:npmPullCli { cliOptions: { _: [], '$0': 'node_modules/.bin/npm-pull' } } +0ms
  @deep-foundation/npm-automation:npm-pull { param: { packageName: undefined, packageVersion: undefined } } +0ms
  @deep-foundation/npm-automation:npm-pull { currentDir: '/home/freephoenix888/Programming/deep/deepcase' } +1ms
  @deep-foundation/npm-automation:npm-pull {
  @deep-foundation/npm-automation:npm-pull   packageJsonFilePath: '/home/freephoenix888/Programming/deep/deepcase/package.json'
  @deep-foundation/npm-automation:npm-pull } +0ms
  @deep-foundation/npm-automation:npm-pull { packageName: '@deep-foundation/deepcase', packageVersion: 'latest' } +1ms
[16:20:07.572] git diff

  @deep-foundation/npm-automation:npm-pull {
  @deep-foundation/npm-automation:npm-pull   gitDiffExecResult: {
  @deep-foundation/npm-automation:npm-pull     command: 'git diff',
  @deep-foundation/npm-automation:npm-pull     escapedCommand: 'git diff',
  @deep-foundation/npm-automation:npm-pull     exitCode: 0,
  @deep-foundation/npm-automation:npm-pull     stdout: '',
  @deep-foundation/npm-automation:npm-pull     stderr: '',
  @deep-foundation/npm-automation:npm-pull     all: undefined,
  @deep-foundation/npm-automation:npm-pull     failed: false,
  @deep-foundation/npm-automation:npm-pull     timedOut: false,
  @deep-foundation/npm-automation:npm-pull     isCanceled: false,
  @deep-foundation/npm-automation:npm-pull     killed: false
  @deep-foundation/npm-automation:npm-pull   }
  @deep-foundation/npm-automation:npm-pull } +14ms
[16:20:07.586] npm install "@deep-foundation/deepcase@latest" --no-save
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms +0ms
  agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free +894msse Completed in 488ms

changed 7 packages, and audited 2408 packages in 5s

183 packages are looking for funding
  run `npm fund` for details

56 vulnerabilities (22 moderate, 33 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
  @deep-foundation/npm-automation:npm-pull {
  @deep-foundation/npm-automation:npm-pull   nodeModuleDirectoryPath: '/home/freephoenix888/Programming/deep/deepcase/node_modules/@deep-foundation/deepcase'
  @deep-foundation/npm-automation:npm-pull } +5s
/home/freephoenix888/Programming/deep/deepcase/node_modules/fs-extra/lib/copy/copy.js:216
          return cb(new Error(`Cannot copy '${resolvedSrc}' to a subdirectory of itself, '${resolvedDest}'.`))
                    ^

Error: Cannot copy '../@deep-foundation/deeplinks/call.cjs' to a subdirectory of itself, '../@deep-foundation/deeplinks/call.cjs'.
    at /home/freephoenix888/Programming/deep/deepcase/node_modules/fs-extra/lib/copy/copy.js:216:21
    at FSReqCallback.oncomplete (node:fs:200:23)

Node.js v18.17.1
```

**Comment by FreePhoenix888** [comment]
@Konard , have any idea why this error happens in deepcase?
