### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'version')

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/npm-automation#6]
```
freephoenix888@freephoenix888:~/Programming/deep/capacitor-motion$ npm run npm-install -- --name="@deep-foundation/capacitor-device" --version="10.0.1"

> @deep-foundation/capacitor-motion@1.2.6 npm-install
> npm-install --name=@deep-foundation/capacitor-device --version=10.0.1


changed 4 packages, and audited 1631 packages in 28s

130 packages are looking for funding
  run `npm fund` for details

58 vulnerabilities (40 moderate, 18 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

(node:83017) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/dist/npm-install.js:34
    deepJson.dependencies[deepJsonDependencyIndex].version =
                                                           ^

TypeError: Cannot set properties of undefined (setting 'version')
    at npmInstall (file:///home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/dist/npm-install.js:34:60)
    at async main (file:///home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/dist/npm-install-cli.js:17:5)

Node.js v18.14.0
```

**Comment by FreePhoenix888** [comment]
Fixed in https://github.com/deep-foundation/npm-automation/commit/523de047c5365e348ec4e288932a4bacd670c832
