### ISSUE TITLE
`Invalid Version: ~0.0.2`

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/npm-automation#7]
```
freephoenix888@freephoenix888:~/Programming/deep/capacitor-motion$ npm run npm-release -- --new-version major

> @deep-foundation/capacitor-motion@1.2.6 npm-release
> npm-release --new-version major

(node:44089) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
@deep-foundation/core, @deep-foundation/capacitor-device, @freephoenix888/object-to-links-async-converter are added to package.json because they exist in deep.json
/home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
            ^

TypeError: Invalid Version: ~0.0.2
    at new SemVer (/home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/node_modules/semver/classes/semver.js:38:13)
    at compare (/home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/node_modules/semver/functions/compare.js:3:32)
    at Object.gt (/home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/node_modules/semver/functions/gt.js:2:29)
    at file:///home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/dist/sync-dependencies.js:29:49
    at Array.forEach (<anonymous>)
    at syncDependencies (file:///home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/dist/sync-dependencies.js:28:27)
    at async npmRelease (file:///home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/dist/npm-release.js:22:5)
    at async main (file:///home/freephoenix888/Programming/deep/capacitor-motion/node_modules/@deep-foundation/npm-automation/dist/npm-release-cli.js:19:5)

Node.js v18.14.0
```

**Comment by FreePhoenix888** [comment]
Fixed in https://github.com/deep-foundation/npm-automation/commit/653198c56044f73677d75d30ff3708abd4f92ce5
