### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Konard** [deep-foundation/npm-automation#8]
![Screenshot_20230702_204059](https://github.com/deep-foundation/npm-automation/assets/1431904/ac98f8d3-0c82-453a-b7db-cc21346f4707)

```
gitpod /workspace/npm-packager (main) $ npm run npm-pull

> @deep-foundation/npm-packager@0.0.25 npm-pull
> npm-pull

(node:910) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:910) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1172:7)
    at npmPull (file:///workspace/npm-packager/node_modules/@deep-foundation/npm-automation/dist/npm-pull.js:38:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///workspace/npm-packager/node_modules/@deep-foundation/npm-automation/dist/npm-pull-cli.js:17:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.0
```

https://github.com/deep-foundation/npm-packager/blob/c25eae86544786ec8e7659dea45cf6c70a498c2f/package.json#L10-L16
![Screenshot_20230702_204906](https://github.com/deep-foundation/npm-automation/assets/1431904/12ad9844-0b2f-4afe-9b11-151cbb7d5887)

![Screenshot_20230702_204816](https://github.com/deep-foundation/npm-automation/assets/1431904/260bd3ca-7062-4849-9430-27e4de1889f0)

in 3.0.9

**Comment by Konard** [comment]
```
gitpod /workspace/npm-packager (main) $ npm run npm-pull

> @deep-foundation/npm-packager@0.0.25 npm-pull
> npm-pull

(node:2101) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2101) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1172:7)
    at npmPull (file:///workspace/npm-packager/node_modules/@deep-foundation/npm-automation/dist/npm-pull.js:39:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///workspace/npm-packager/node_modules/@deep-foundation/npm-automation/dist/npm-pull-cli.js:17:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.0
```

again in 3.0.12
